# Generated by Django 3.2 on 2021-09-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLUpdates',
            fields=[
                ('film_work_id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"content"."etl_updates"',
            },
        ),
        migrations.AddIndex(
            model_name='etlupdates',
            index=models.Index(fields=['updated_at'], name='etl_updates_updated_at_idx'),
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO "content"."etl_updates" ("film_work_id", "updated_at") 
                SELECT "id", "updated_at" 
                FROM "content"."film_work";
            """,
            reverse_sql="""
                TRUNCATE TABLE "content"."etl_updates";
            """,
        ),
    ]
