version: '3'

services:
  movies:
    build: ./movies_admin
    command: gunicorn config.wsgi:application --workers 3 --log-level info --access-logfile - --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.prod
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/usr/src/app/static
    depends_on:
      - movies
    ports:
      - 80:80

volumes:
  postgres_data:
  static_volume:
